Don't pass the "format" argument of struct.pack as a bytestring.
It's the format argument, not actual data, and it's perfectly happy to
be a plain str. But using a b'' string in python3 means we cannot
interpolate an int inside, so we get the error message:

>>> serialize_binary('foo', True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/eschwartz/git/calibre/src/calibre/gui2/win_file_dialogs.py", line 61, in serialize_binary
    return struct.pack(b'=B%ssB' % len(key), len(key), key, int(val))
TypeError: %b requires a bytes-like object, or an object that implements __bytes__, not 'int'